version: "3.8"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: host
    volumes:
      - /mnt/external_drive/media:/media
      - /path/to/config:/config
    restart: unless-stopped

  metube:
    image: alexta69/metube:latest
    container_name: metube
    ports:
      - 8081:8081
    volumes:
      - /mnt/external_drive/downloads:/downloads
    restart: unless-stopped